// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB43His6ONotjfK8Ouu-JQXnCaVkmJTfc',
    appId: '1:1074312257034:web:1b21495effddfbc9d709f3',
    messagingSenderId: '1074312257034',
    projectId: 'recipe-roulette-74944',
    authDomain: 'recipe-roulette-74944.firebaseapp.com',
    storageBucket: 'recipe-roulette-74944.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqq8KAeowDS6V1lR6fqNG9KkQg5b89InQ',
    appId: '1:1074312257034:android:2df0122cdb009d8bd709f3',
    messagingSenderId: '1074312257034',
    projectId: 'recipe-roulette-74944',
    storageBucket: 'recipe-roulette-74944.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeYD8OGw1P4rzQTR4F_Sm6jvkbBf_AFVE',
    appId: '1:1074312257034:ios:4236edd76a3cd811d709f3',
    messagingSenderId: '1074312257034',
    projectId: 'recipe-roulette-74944',
    storageBucket: 'recipe-roulette-74944.appspot.com',
    iosClientId:
        '1074312257034-96q5ofn9ub2aqf1brvakrnsrs4fk34fg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeYD8OGw1P4rzQTR4F_Sm6jvkbBf_AFVE',
    appId: '1:1074312257034:ios:4236edd76a3cd811d709f3',
    messagingSenderId: '1074312257034',
    projectId: 'recipe-roulette-74944',
    storageBucket: 'recipe-roulette-74944.appspot.com',
    iosClientId:
        '1074312257034-96q5ofn9ub2aqf1brvakrnsrs4fk34fg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
